services:
  postgres:
    container_name: finn-job-ads-postgres
    build: .
    pull_policy: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=321
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow:
    container_name: finn-job-ads-airflow
    image: apache/airflow:slim-latest-python3.11
    entrypoint: /bin/bash /opt/airflow/start_airflow.sh
    ports:
      - "8080:8080"
    volumes:
      - airflow-data:/opt/airflow/dags
      - ../dags:/opt/airflow/dags
      - ./airflow_requirements.txt:/opt/airflow/requirements.txt
      - ./start_airflow.sh:/opt/airflow/start_airflow.sh
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:321@postgres:5432/ingestion

volumes:
  postgres-data:
  airflow-data:
